'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Localization
    Public Property Id As Integer
    Public Property X As Nullable(Of Decimal)
    Public Property Y As Nullable(Of Decimal)

    Public Overridable Property Jedi As ICollection(Of Jedi) = New HashSet(Of Jedi)
    Public Overridable Property Robot As ICollection(Of Robot) = New HashSet(Of Robot)

End Class
