'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Robot
    Public Property Id As Integer
    Public Property Name As String
    Public Property LocalizationId As Nullable(Of Integer)
    Public Property LifePoint As Nullable(Of Integer)

    Public Overridable Property Localization As Localization

End Class
