'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class starwars_dbEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=starwars_dbEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Robot() As DbSet(Of Robot)
    Public Overridable Property Jedi() As DbSet(Of Jedi)
    Public Overridable Property Localization() As DbSet(Of Localization)

End Class
